#!/bin/bash  # Shebang line to specify that the script should be run using the Bash shell

# System Report Script

# Gathering Data

USERNAME=$(whoami)  # Get the current logged-in username
DATETIME=$(date +"%Y-%m-%d %H:%M:%S")  # Get the current date and time in a human-readable format
HOSTNAME=$(hostname)  # Get the system's hostname
OS=$(source /etc/os-release && echo "$PRETTY_NAME")  # Get the OS name and version from /etc/os-release
UPTIME=$(uptime -p)  # Get the system uptime in a pretty format

# Gather CPU information
CPUINFO=$(lshw -class processor | grep -m 1 'product' | awk -F': ' '{print $2}')  # Get the processor make and model
CPUSPEED=$(lshw -class processor | grep -m 1 'capacity' | awk -F': ' '{print $2}')  # Get the current processor speed

# Memory and storage information
RAM=$(free -h | grep Mem | awk '{print $2}')  # Get the total amount of RAM installed
DISKS=$(lsblk -o MODEL,SIZE | grep -v "loop\|NAME")  # List model and size of all installed disks, excluding loop devices

# Video card information
VIDEO=$(lshw -class display | grep -m 1 'product' | awk -F': ' '{print $2}')  # Get the make and model of the video card

# Network information
FQDN=$(hostname -f)  # Get the fully qualified domain name (FQDN)
IPADDR=$(hostname -I | awk '{print $1}')  # Get the host's primary IP address (IPv4/IPv6)
GATEWAY=$(ip route | grep default | awk '{print $3}')  # Get the gateway IP address from the routing table
DNSSERVER=$(cat /etc/resolv.conf | grep 'nameserver' | awk '{print $2}')  # Get the primary DNS server IP from resolv.conf

# Network interface details
NETCARD=$(lshw -class network | grep -m 1 'product' | awk -F': ' '{print $2}')  # Get the make and model of the network card
NETIP=$(ip a | grep -m 1 'inet ' | awk '{print $2}')  # Get the IP address of the first network interface in CIDR format

# System Status

USERS=$(who | awk '{print $1}' | sort | uniq | paste -sd ",")  # Get a list of unique users currently logged in
DISKSPACE=$(df -h --output=target,avail | grep '^/')  # Display available disk space for each mount point
PROCCOUNT=$(ps -e | wc -l)  # Count the total number of running processes
LOADAVG=$(uptime | awk -F'load average:' '{print $2}' | sed 's/, /, /g')  # Get system load averages over the last 1, 5, and 15 minutes
MEMALLOC=$(free -h | grep -E 'Mem|Swap')  # Display memory and swap usage
LISTENPORTS=$(ss -tuln | grep LISTEN | awk '{print $5}' | cut -d':' -f2 | paste -sd ",")  # List all ports that are currently listening
UFWRULES=$(sudo ufw status)  # Display UFW firewall rules (requires sudo)

# Displaying the Report using a here document (EOF)
cat <<EOF

System Report generated by $USERNAME, $DATETIME

System Information
------------------
Hostname: $HOSTNAME
OS: $OS
Uptime: $UPTIME

Hardware Information
--------------------
CPU: $CPUINFO
Speed: $CPUSPEED
RAM: $RAM
Disks: 
$DISKS
Video: $VIDEO

Network Information
-------------------
FQDN: $FQDN
Host Address: $IPADDR
Gateway IP: $GATEWAY
DNS Server: $DNSSERVER

Interface Name: $NETCARD
IP Address: $NETIP

System Status
-------------
Users Logged In: $USERS
Disk Space: 
$DISKSPACE
Process Count: $PROCCOUNT
Load Averages: $LOADAVG
Memory Allocation: 
$MEMALLOC
Listening Network Ports: $LISTENPORTS
UFW Rules: 
$UFWRULES

EOF
